stages:
    - build
    - test
    - qa
    - deploy

image: registry.johnnei.org:443/docker-images/maven:lts

variables:
  MAVEN_OPTS: -Dmaven.repo.local=/cache/.repository

# Compile the code, must succeed before we start testing.
build:
    stage: build
    script: "mvn -B clean compile"

# Run the quick test suite (Unit tests mostly)
quicktests:
    stage: test
    script: "mvn -B test --fail-at-end"
    artifacts:
      expire_in: 1 week
      paths:
      - "**/target/site/jacoco/jacoco.xml"
      - "**/target/surefire-reports/*.xml"
      reports:
        junit: "**/target/surefire-reports/*.xml"

# Run the integration test suite (Unit tests which don't use mocks and commonly exclude mock usages)
integration-tests:
    stage: test
    script: "mvn -B verify --fail-at-end -DskipUTs=true"
    artifacts:
      when: always
      expire_in: 1 week
      paths:
      - "**/target/*.log"
      - "**/target/site/jacoco-it/jacoco.xml"
      - "**/target/failsafe-reports/*.xml"
      reports:
        junit: "**/target/failsafe-reports/*.xml"

# PR Analysis
sonarqube:
    stage: qa
    script: "mvn -B compile test-compile sonar:sonar -Dsonar.host.url=https://sonarqube.johnnei.org -Dsonar.login=$SONAR_TOKEN"
    only: ["/^feature\\/.*$/"]
    dependencies: []

# Run a sonar analysis.
sonarqube.johnnei.org:
    stage: qa
    script: "mvn -B compile test-compile sonar:sonar -Dsonar.host.url=https://sonarqube.johnnei.org -Dsonar.login=$SONAR_TOKEN"
    only: ["develop"]
    dependencies:
      - quicktests
      - integration-tests

pages:
    stage: deploy
    dependencies: []
    image: ruby:2.3
    script:
    - cd docs
    - bundle install
    - bundle exec jekyll build -d ../public
    only: ["develop"]
    artifacts:
      paths:
        - public

test deployment:
    stage: test
    script: "mvn -B -Prelease clean verify -DskipTests -Dgpg.passphrase=$GPG_PASS"
    tags: ["deploy"]
    dependencies: []
    variables:
      MAVEN_OPTS: ""
    artifacts:
      expire_in: 1 week
      paths:
      - "**/target/*.jar"
      - "**/target/*.jar.asc"
    only: ["/^release\\/.*$/"]

deploy to maven central:
    stage: deploy
    script: "mvn -B -Prelease clean deploy -DskipTests -Dgpg.passphrase=$GPG_PASS"
    environment: MavenCentral
    dependencies: []
    variables:
      MAVEN_OPTS: ""
    artifacts:
      paths:
      - "**/target/*.jar"
      - "**/target/*.jar.asc"
    when: manual
    tags: ["deploy"]
    only:
      - tags
