stages:
    - build
    - test
    - qa
    - deploy

image: registry.johnnei.org:443/docker-images/maven:lts

variables:
  MAVEN_OPTS: -Dmaven.repo.local=/cache/.repository

# Compile the code, must succeed before we start testing.
build:
    tags: [ "docker" ]
    stage: build
    script: "mvn -B clean compile"

# Run the quick test suite (Unit tests mostly)
quicktests:
    stage: test
    tags: [ "docker" ]
    script: "mvn -B test --fail-at-end"
    artifacts:
      expire_in: 1 week
      paths:
      - "**/target/site/jacoco/jacoco.xml"
      - "**/target/surefire-reports/*.xml"
      reports:
        junit: "**/target/surefire-reports/*.xml"

# Run the integration test suite (Unit tests which don't use mocks and commonly exclude mock usages)
integration-tests:
    stage: test
    tags: [ "docker" ]
    script: "mvn -B verify --fail-at-end -DskipUTs=true"
    artifacts:
      when: always
      expire_in: 1 week
      paths:
      - "**/target/*.log"
      - "**/target/site/jacoco-it/jacoco.xml"
      - "**/target/failsafe-reports/*.xml"
      reports:
        junit: "**/target/failsafe-reports/*.xml"

# Run a sonar analysis.
sonarqube.johnnei.org:
    stage: qa
    tags: [ "docker" ]
    script: "mvn -B compile test-compile sonar:sonar -Dsonar.host.url=https://sonarqube.johnnei.org -Dsonar.login=$SONAR_TOKEN"
    only: ["develop"]
    dependencies:
      - quicktests
      - integration-tests

site:
  stage: qa
  tags:
    - docker
  script:
    - "mvn -B test-compile site:site"
  only:
    - develop
  dependencies: []
  needs:
    - build
  artifacts:
    paths:
      - "target/site/*"
      - "target/site/css/*"
      - "target/site/images/*"
      - "target/site/images/logos/*"

pages:
    stage: deploy
    image: ruby:2.7.2
    tags: [ "docker" ]
    dependencies: []
    needs: []
    script:
    - cd docs
    - bundle install
    - bundle exec jekyll build -d ../public
    only: ["develop"]
    artifacts:
      paths:
        - public

test deployment:
  stage: test
  script:
    - "echo $GPG_PRIVATE_KEY | base64 -d | gpg --import --batch"
    - "mkdir -p ~/.m2"
    - "cp $OSSRH_SETTINGS ~/.m2/settings.xml"
    - "mvn -B -Prelease -pl !bittorrent-integration-tests clean verify -DskipTests -Dgpg.passphrase=$GPG_PASS"
  tags: [ "docker" ]
  dependencies: [ ]
  variables:
    MAVEN_OPTS: ""
  artifacts:
    expire_in: 1 week
    paths:
      - "**/target/*.jar"
      - "**/target/*.jar.asc"
  only: [ "/^release\\/.*$/" ]

deploy to maven central:
  stage: deploy
  script:
    - "echo $GPG_PRIVATE_KEY | base64 -d | gpg --import --batch"
    - "mkdir -p ~/.m2"
    - "cp $OSSRH_SETTINGS ~/.m2/settings.xml"
    - "mvn -B -Prelease -pl !bittorrent-integration-tests clean deploy -DskipTests -Dgpg.passphrase=$GPG_PASS"
  environment:
    name: "MavenCentral"
    url: "https://search.maven.org/search?q=g:org.johnnei%20javatorrent"
  dependencies: [ ]
  variables:
    MAVEN_OPTS: ""
  artifacts:
    paths:
      - "**/target/*.jar"
      - "**/target/*.jar.asc"
  when: manual
  tags: [ "docker" ]
  only:
    - tags
